MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.11.24

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,37 +4,60 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
+    - CONFIG=osx_python2.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "fXWEtI8TzsmV3HJGSiE7ZV78dBMqG3BoOZm9igwQ3o92J0Q+aaXDRkK3LAArdK5kzr1Q2f+O4fZvCk283QdipkQNlmcXAlqWzgnR87HdXQAYwn3nAe/5U+VRbAgsUuj2O4k+88VhlNIdkMxHtTXYi9S19URyn3cchUZH5OEECKTUfMjKf4sUMiLQVl72dF0riSVYEM9PMD87JQouv6V95UDkvpKr7Arptd0IyvZk0g3SOIHtsi6IHTTSw2rRqDWsb94QhV/ns7N6Xwt9ta6CZ7ArA3sjZs+xuKCg8zGUS8tPIP+1Hl3JPjyHKJX6RPN3qHd1ppKdlGA/qQ90QRxGRq9CFucet2NZkelHgFWeZFnM0rU11Bh2o39pXtvrXxmN3tm/aDi0s2TDmBjDx4h0PzFOvsBbhw+jX/Ei0H55ZgmP+VIXJfGChSAmTbvSXtsAqSOa1e2Z+z/z/li121r7/fy3/q26f0Wbp88TZwEkv2Y7HSsztj2MVR5N8nu93MfOyi0JLuey9uxDqRds2hkZeJDcLybQPRB/OfCoWWKuczno19cbalwalGtAihlYrxR9EsqlyczX9aJpqsQpY+8gQTiZLuXnoVDSt5JqokLvgrtICBge0xcyy6DEqaeMGrjIyDuW/vjOY5+nx6jDcGJEyKIIzbJ53bpZ9j8bcl2qdgg="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
-      MINICONDA_URL="http://repo.continuum.io/miniconda"
+      echo ""
+      echo "Installing a fresh version of Miniconda."
+      MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
-      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
+      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
